### ISSUE TITLE
(P => Q) => R

### ISSUE THREAD

**Issue by RonaldBilbit** [MostAwesomeDude/brismu#3]
Hi,

How to say, in Lojban, (P => Q) => R?

(broda => brode) => brodi

Using your suggestion (https://brismu.systems/ax-s.html):

> Step 1. (broda => brode) => brodi
> Step 2. ganai (broda => brode) gi brodi
> Step 3. ganai (ganai broda gi brode) gi brodi
> Step 4. ganai ganai broda gi brode gi brodi
> 

Is this correct?

Is the following pseudo-sentence ill-formed? If so, according to which explicit rule of the CLL?

> ganai (ganai broda) gi (brode gi bordi)

Do you think the point of view I express here is correct ?

Source: 
https://brismu.systems/ax-s.html

**Comment by MostAwesomeDude** [comment]
It looks like you've got it right. You can check whether a *bridi* is grammatical using a CLL-compatible parser like [jboski](https://jboski.lojban.org/). For example, we can put [your example in jboski](https://jboski.lojban.org/?text=ganai%20ganai%20broda%20gi%20brode%20gi%20brodi) and see the corresponding parse tree:

    [1ga nai [if] [2ga nai [if] [3«4broda predicate var 1??»4]3 gi [then] [5«6brode predicate var 2??»6]5]2 gi [then] [7«8brodi predicate var 3??»8]7]1
